import { RequiredDataFromCollectionSlug } from 'payload'

export const franchiseInquiryForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Franchise Inquiry Form',
  submitButtonLabel: 'Submit inquiry',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
      children: [
        {
          type: 'heading',
          tag: 'h2',
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for your interest in becoming a Tim Hortons franchisee.',
              version: 1,
            },
          ],
        },
        {
          type: 'paragraph',
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
          textFormat: 0,
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Our franchise development team reviews every inquiry. We will follow up if your background matches a current opportunity.',
              version: 1,
            },
          ],
        },
      ],
    },
  },
  emails: [
    {
      emailFrom: '"Tim Hortons Franchising" <franchising@timhortons.example>',
      emailTo: '{{email}}',
      subject: 'We received your franchise inquiry',
      message: {
        root: {
          type: 'root',
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'paragraph',
              direction: 'ltr',
              format: '',
              indent: 0,
              version: 1,
              textFormat: 0,
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thanks for reaching out about Tim Hortons franchising. Watch your inbox for next steps.',
                  version: 1,
                },
              ],
            },
          ],
        },
      },
    },
  ],
  fields: [
    {
      name: 'first-name',
      blockName: 'first-name',
      blockType: 'text',
      label: 'First name',
      required: true,
      width: 50,
    },
    {
      name: 'last-name',
      blockName: 'last-name',
      blockType: 'text',
      label: 'Last name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 50,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'number',
      label: 'Phone',
      required: true,
      width: 50,
    },
    {
      name: 'province',
      blockName: 'province',
      blockType: 'state',
      label: 'Preferred province / state',
      required: true,
      width: 50,
    },
    {
      name: 'city',
      blockName: 'city',
      blockType: 'text',
      label: 'Preferred city / market',
      required: true,
      width: 50,
    },
    {
      name: 'liquid-capital',
      blockName: 'liquid-capital',
      blockType: 'select',
      label: 'Liquid capital available',
      required: true,
      width: 100,
      options: [
        { label: 'Under $250,000', value: 'under-250k' },
        { label: '$250,000 – $500,000', value: '250k-500k' },
        { label: '$500,000 – $1,000,000', value: '500k-1m' },
        { label: 'Over $1,000,000', value: 'over-1m' },
      ],
    },
    {
      name: 'restaurant-experience',
      blockName: 'restaurant-experience',
      blockType: 'select',
      label: 'Restaurant or multi-unit operating experience',
      required: true,
      width: 100,
      options: [
        { label: 'None', value: 'none' },
        { label: '1–3 years', value: '1-3' },
        { label: '4–10 years', value: '4-10' },
        { label: '10+ years', value: '10-plus' },
      ],
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Tell us about yourself',
      required: false,
      width: 100,
    },
  ],
}
